### ISSUE TITLE
Request for DryIoc equivalent

### ISSUE THREAD

**Issue by animechitransh** [alsiola/FlyoutManager#1]
Request(not an issue), feel free to ignore.

Could you please create dryIoc equivalent of this package. I tried simpler version with it but couldn't get it to work (I am new to WPF, MVVM & Prism)

**Comment by alsiola** [comment]
Hi @animechitransh - thanks for the request. To be honest I don't work in the C#/.NET ecosystem these days, and I'm very out of touch with developments in Prism, MahApps.Metro or the wider ecosystem. With this in mind, it would be very difficult for me to help you here, although if you wanted to open a pull request with any changes that would help you to integrate it with dryIoc or any other framework, I'd be more than happy to work with you on it.

**Comment by animechitransh** [comment]
Thanks i was able to figure it out, its not as good as yours but serves the purpose
https://github.com/animechitransh/Prism-DryIoc-MahappsFlyout-Demo
